### PR TITLE
Remove cache, omelette and .yarn/cache folders of final image

### LINKED ISSUE #28: Remove cache, omelette and .yarn/cache folders when building the final image
In the new versions of Volto, when running `yarn build`, folders `cache`, `omelette` and `.yarn/cache` are created. These folders are not needed in the final image and can be removed before copying the files to the final image.

### PR DESCRIPTION
**Pull request by wesleybl**
This folder is not needed to run Volto.

fixes #28

### CODE REVIEW

**Comment by wesleybl** [comment]
@gforcada can you please do with this repository something similar to what you did in: https://github.com/plone/mr.roboto/pull/98

**Comment by gforcada** [comment]
Sure :)

**Comment by gforcada** [comment]
[mr.roboto](https://github.com/plone/mr.roboto/pull/105) 😄 

Though, with the backend @davisagli was pointing that you should start writing a change log entry, wouldn't be the same here as well? 🤔 

Anyway, meanwhile the check will not appear 😄

**Comment by gforcada** [comment]
🚀 The changes has been deployed 🤖

**Comment by wesleybl** [comment]
@gforcada Thanks!

**Review by jensens — APPROVED** [review]

**Comment by wesleybl** [comment]
@sneridagh @ericof can you take a look here please?

**Review by ericof — APPROVED** [review]

**Pull request merged**
